version: "3.1"

services:
  airflow:
    image: mkenjis/airflow_xtd_spark_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp1
    networks:
      - mynet
    ports:
      - 8080:8080
    environment:
      - HADOOP_HOST_MASTER=hdpmst

networks:
  mynet:
    external:
       name: mynet